#!/usr/local/bin/bash

#set -u

_FLDR_CLOUD=/Users/Shared/CLOUD
_FLDR_REPOS=$_FLDR_CLOUD/Development.GitHub/Repositories.FromGithub/repositories/

_LINK_GITHUB=https://github.com

(
	cd $_FLDR_REPOS
	ls -1
)						|\
grep -v work			|\
sort					|\
while read _TOOLBOX
do
	_NAME="${_TOOLBOX%-*}"
	_TYPE="${_TOOLBOX##*-}"

	if [[ "$_TYPE" == "toolbox" ]]; then
		_TYPE=""
	else
		_TYPE=" ${_TYPE^}"
	fi

	_IMAGE="${_NAME,,}.png"
	if [[ ! -f "assets/img/$_IMAGE" ]]; then
		_IMAGE="placeholder.png"
	fi

	echo "- title: ${_NAME^}${_TYPE}"
	echo "  link: https://github.com/$_TOOLBOX"
	echo "  img: ${_IMAGE}"
	echo ""
done | tee _data/toolboxes.yml-NEW